version: 2
jobs:
  build:
    docker:
      - image: haskell:8.6.3
        environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v6-{{ checksum "package.yaml" }}
            - stack-v6-
      - run:
          name: Prepare stack
          command: |
            stack upgrade
            export PATH=~/.local/bin:$PATH
            stack config set system-ghc --global true
            stack config set install-ghc --global false
            stack --version
      - run:
          name: Install system dependencies
          command: |
            apt-get -qq update
            apt-get -qqy install pkg-config libxml2-dev dbus-x11 curl
            curl -sSL https://github.com/sol/hpack/releases/download/0.31.0/hpack_linux.gz | gunzip > /usr/local/bin/hpack
            chmod +x /usr/local/bin/hpack
            stack build weeder hlint
      - run: stack build --test --pedantic --no-run-tests
      - save_cache:
          key: stack-v6-{{ checksum "package.yaml" }}
          paths: [ ~/.stack ]
          when: always
      - run:
          name: Test
          command: |
            mkdir report
            stack test
      - run:
          name: Weeder
          command: |
            stack exec -- weeder --match
      - run:
          name: HLint
          command: |
            stack exec -- hlint src test
      - store_test_results:
          path: ./report
      - store_artifacts:
          path: /root/project/report
