#!/bin/bash
#
# This is a stub for the pacmd that stores all its state in a local
# state file.

STATE_FILE=pa-state~
if [[ ! -f $STATE_FILE ]]; then
  echo "STATE_FILE environment variable does not point to a file" >&2
  exit 1
fi

if [[ "$1" == "dump" ]]; then
  cat $STATE_FILE
elif [[ "$1" =~ ^set-sink-[a-z]+$ ]]; then
  sed -i "/^$1 $2/c $*" $STATE_FILE
else
  sed -i "/^$1/c $*" $STATE_FILE
fi
