version: 2
jobs:
  build_test:
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v6-{{ checksum "package.yaml" }}
            - stack-v6-
      - run:
          name: Prepare stack
          command: |
            stack upgrade
            export PATH=~/.local/bin:$PATH
            stack config set system-ghc --global true
            stack config set install-ghc --global false
            stack --version
      - run:
          name: Install system dependencies
          command: |
            apt-get -qq update
            apt-get -qqy install pkg-config libxml2-dev dbus-x11
            stack build weeder hlint
      - run: stack build --test --pedantic --no-run-tests --flag pa-volume-control:static
      - save_cache:
          key: stack-v6-{{ checksum "package.yaml" }}
          paths: [ ~/.stack ]
          when: always
      - run:
          name: Test
          command: |
            mkdir report
            stack test
      - run:
          name: Weeder
          command: |
            stack exec -- weeder --match
      - run:
          name: HLint
          command: |
            stack exec -- hlint src test
      - run:
          name: Copy artifacts to workspace
          command: |
            mkdir ~/workspace
            cp -r $(stack exec -- which pa-volume-control) ~/workspace
      - persist_to_workspace:
          root: ~/workspace
          paths: [ "*" ]
      - store_test_results:
          path: ./report
      - store_artifacts:
          path: /root/project/report

  release:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Create release
          command: |
            tag="$CIRCLE_TAG"
            release_name="$tag $(date --iso=date)"

            export GITHUB_REPO="$CIRCLE_PROJECT_REPONAME"
            export GITHUB_USER="$CIRCLE_PROJECT_USERNAME"

            ./ci/gothub release \
              --user geigerzaehler \
              --repo pa-volume-control \
              --tag "$tag" \
              --name "$release_name" \
              --draft

            ./ci/gothub upload \
              --user geigerzaehler \
              --repo pa-volume-control \
              --tag "$tag" \
              --name "pa-volume-control.$tag-linux-$(uname -m)" \
              --file "$HOME/workspace/pa-volume-control"

workflows:
  version: 2
  build_deploy:
    jobs:
    - build_test:
        filters:
          tags: {only: /^v.+$/}
    - release:
        requires: [build_test]
        filters:
          branches: {ignore: /.*/}
          tags: {only: /^v.+$/}
